#!/usr/bin/env bash
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
ISSUE_REFERENCE_LINE=`head -n3 $INPUT_FILE | tail -n1`
PATTERN="^Closes #[0-9]+\.$"
if [ -z "${START_LINE}" ]; then
  printf "Commit message title cannot be empty.\n"
  exit 1
fi
if ! [[ $ISSUE_REFERENCE_LINE =~ $PATTERN ]]; then
  printf "Bad commit message\nThe 3rd line ($ISSUE_REFERENCE_LINE) has to contain an issue reference in the following format: \nCloses #1234.\n"
  exit 1
fi
