# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven build - clean test verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Other versions of java can be configured as well - https://github.com/actions/setup-java#basic
        java: [14.0.1]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 14
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          - id: install-secret-key
            name: Install gpg secret key
            run: |
              cat <(echo -e "${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}") | gpg --batch --import
              gpg --list-secret-keys --keyid-format LONG
          - id: publish-to-central
            name: Publish to Central Repository
            env:
              MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
              MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
            run: |
              mvn \
                --no-transfer-progress \
                --batch-mode \
                -Dgpg.passphrase=${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }} \
                -e clean test verify --file pom.xml
